### ISSUE TITLE
Test cases

### ISSUE THREAD

**Issue by bbsachinbb** [riemann/riemann-tools#195]
Hi all,
Where can i find test cases for riemann tools

**Comment by smortex** [comment]
Since you opened this issue, and starting with version 1.0.0, the project has some unit tests using RSpec.  Not all code is tested unfortunately, but we try to add tests when new features are added and we also did some refactoring to make writing these tests easier.  We also have setup CI that run the test suite for each commit / pull request.

Of course, if people want to contribute tests, we are happy to review pull requests!

I will close this issue assuming this is the kind of information you where interested in. If I missed your point, feel free to reopen the issue and clarify your request. Thanks!
